# -*- coding: utf-8 -*-
"""常量定义"""

# 关键词定义
KEYWORDS = {
    "name": ["氏名", "氏 名", "名前", "フリガナ", "Name", "名　前", "姓名"],
    "age": ["年齢", "年龄", "年令", "歳", "才", "Age", "年　齢", "生年月", "満"],
    "gender": ["性別", "性别", "Gender", "性　別"],
    "nationality": ["国籍", "出身国", "出身地", "Nationality", "国　籍"],
    "experience": [
        "経験年数",
        "実務経験",
        "開発経験",
        "ソフト関連業務経験年数",
        "IT経験",
        "業務経験",
        "経験",
        "実務年数",
        "Experience",
        "エンジニア経験",
        "経験年月",
        "職歴",
        "IT経験年数",
        "コンピュータソフトウエア関連業務",
        "実務年数",
    ],
    "arrival": [
        "来日",
        "渡日",
        "入国",
        "日本滞在年数",
        "滞在年数",
        "在日年数",
        "来日年",
        "来日時期",
        "来日年月",
        "来日年度",
    ],
    "japanese": [
        "日本語",
        "日語",
        "JLPT",
        "日本語能力",
        "語学力",
        "言語能力",
        "日本語レベル",
        "Japanese",
    ],
    "education": ["学歴", "学校", "大学", "卒業", "専門学校", "高校", "最終学歴"],
    "skills": [
        "技術",
        "スキル",
        "言語",
        "DB",
        "OS",
        "フレームワーク",
        "ツール",
        "Skills",
        "开发语言",
        "プログラミング言語",
        "データベース",
        "開発環境",
        "技術経験",
    ],
}

# 有效的国籍列表
VALID_NATIONALITIES = [
    "中国",
    "日本",
    "韓国",
    "ベトナム",
    "フィリピン",
    "インド",
    "ネパール",
    "アメリカ",
    "ブラジル",
    "台湾",
    "タイ",
    "インドネシア",
    "バングラデシュ",
    "スリランカ",
    "ミャンマー",
    "カンボジア",
    "ラオス",
    "モンゴル",
]

# 技能标记符号
SKILL_MARKS = ["◎", "○", "△", "×", "★", "●", "◯", "▲", "※"]

# 有效技能列表
VALID_SKILLS = {
    # 编程语言
    "Java",
    "JAVA",
    "Python",
    "JavaScript",
    "TypeScript",
    "C",
    "C++",
    "C#",
    "C/C++",
    "PHP",
    "Ruby",
    "Go",
    "Kotlin",
    "Swift",
    "Scala",
    "Rust",
    "VB.NET",
    "VB",
    "VBA",
    "COBOL",
    "Perl",
    "R",
    "Objective-C",
    # 前端
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    "React",
    "React.js",
    "Vue",
    "Vue.js",
    "Angular",
    "jQuery",
    "Bootstrap",
    "Webpack",
    "Sass",
    "Less",
    # 后端框架
    "Spring",
    "SpringBoot",
    "SpringMVC",
    "Struts",
    "Struts2",
    "Django",
    "Flask",
    "Rails",
    "Express",
    "Node.js",
    ".NET",
    "ASP.NET",
    "Laravel",
    "Thymeleaf",
    "JSF",
    "JSP",
    "Servlet",
    "Java Servlet",
    "Hibernate",
    "MyBatis",
    "Mybatis",
    "JPA",
    # 数据库
    "MySQL",
    "PostgreSQL",
    "Oracle",
    "SQL Server",
    "SQLServer",
    "MongoDB",
    "Redis",
    "DB2",
    "SQLite",
    "Access",
    "Sybase",
    "Azure SQL DB",
    "PL/SQL",
    "Aurora",
    # 工具和平台
    "AWS",
    "Azure",
    "GCP",
    "Docker",
    "Kubernetes",
    "Git",
    "GitHub",
    "GitLab",
    "SVN",
    "TortoiseSVN",
    "Jenkins",
    "Maven",
    "Gradle",
    # OS
    "Windows",
    "Windows 10",
    "Linux",
    "Unix",
    "Solaris",
    "DOS/V",
    "Win95/98",
    "win10",
    "Ubuntu",
    "CentOS",
    "RedHat",
    # 服务器
    "Apache",
    "Nginx",
    "Tomcat",
    "WebSphere",
    "JBoss",
    "JBOSS",
    "IIS",
    # IDE和工具
    "Eclipse",
    "IntelliJ",
    "VS Code",
    "Visual Studio",
    "Android Studio",
    "NetBeans",
    "Xcode",
    "A5M2",
    "WinMerge",
    "WinSCP",
    "Sourcetree",
    "Postman",
    "Fiddler",
    "Charles",
    "Form Designer",
    # 测试工具
    "JUnit",
    "Junit",
    "Selenium",
    "JMeter",
    "Jmeter",
    "Spock",
    # 其他技术
    "XML",
    "JSON",
    "REST",
    "SOAP",
    "Ajax",
    "Microservices",
    "Shell",
    "Bash",
    "PowerShell",
    "VBScript",
    # 移动开发
    "Android",
    "iOS",
    "React Native",
    "Flutter",
    # 其他框架和库
    "TERASOLUNA",
    "OutSystems",
    "Wacs",
    # Web相关
    "PHP/HTML",
    "Jquery",
    "JAVASCRIPT",
}

# 需要排除的非技能内容模式
EXCLUDE_PATTERNS = [
    r"^\d{4}[-/]\d{2}[-/]\d{2}",
    r"^\d{2,4}年\d{1,2}月",
    r"\d+人",
    r"人以[下上]",
    r"^(基本|詳細)設計$",
    r"^製造$",
    r"^(単体|結合|総合|運用)[試験テスト]",
    r"^保守運用$",
    r"^要件定義$",
    r"^(PM|PL|SL|TL|BSE|SE|PG)$",
    r"^管理$",
    r"管理経験",
    r"^教\s*育$",
    r"業務経歴",
    r"プロジェクト",
    r"^その他$",
    r"^過去の",
    r"【.*】",
    r"^[A-BD-Z]$",
    r"^携帯$",
    r"^E-mail$",
]
